INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:24:28] "GET / HTTP/1.1" 302 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:24:28] "GET /login?next=/ HTTP/1.1" 200 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:24:28] "GET /static/css/auth.css HTTP/1.1" 304 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:24:33] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:24:33] "GET /static/css/auth.css HTTP/1.1" 304 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:24:35] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:24:35] "GET /static/css/auth.css HTTP/1.1" 304 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:26:02] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:26:02] "GET /static/css/auth.css HTTP/1.1" 304 -
ERROR:app:Exception on /register [POST]
Traceback (most recent call last):
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-1-09d2e37b0a7b>", line 110, in register
    if User.query.filter_by(username=username).first():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\sqlalchemy\orm\query.py", line 2754, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\sqlalchemy\orm\query.py", line 2853, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\sqlalchemy\orm\session.py", line 2239, in _execute_internal
    bind = self.get_bind(**bind_arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\flask_sqlalchemy\session.py", line 53, in get_bind
    engines = self._db.engines
              ^^^^^^^^^^^^^^^^
  File "d:\Anaconda39\envs\RAG\Lib\site-packages\flask_sqlalchemy\extension.py", line 690, in engines
    raise RuntimeError(
RuntimeError: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
ERROR:root:500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:27:34] "POST /register HTTP/1.1" 302 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:27:34] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:10.12.100.200 - - [07/Jul/2025 18:27:34] "GET /static/css/auth.css HTTP/1.1" 304 -
500 error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.